# Generated by Django 4.2.6 on 2023-11-04 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_social", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="last_online",
        ),
    ]
