# Generated by Django 4.2.6 on 2023-11-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_social", "0002_remove_profile_last_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
